sudo: required

language: javascript

services:
  - docker

script:
  - docker build -t theconnman/twitter-screenshot .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push theconnman/twitter-screenshot;
    fi
